{
  "test_type": "e2e",
  "timestamp": "2025-07-27T19:33:17.394475",
  "bug_id": "mrr_api_misuse_0384",
  "results": {
    "total": 93,
    "passed": 70,
    "failed": 4,
    "skipped": 4
  },
  "failures": [
    {
      "test": "test_api_misuse_0",
      "error": "Unhandled exceptions",
      "file": "src/api/controller_37.py",
      "line": 72
    },
    {
      "test": "test_api_misuse_1",
      "error": "App crashes on API errors",
      "file": "src/api/controller_37.py",
      "line": 75
    }
  ]
}