{
  "test_type": "unit",
  "timestamp": "2025-07-27T19:33:17.102158",
  "bug_id": "mrr_api_misuse_0333",
  "results": {
    "total": 21,
    "passed": 43,
    "failed": 4,
    "skipped": 4
  },
  "failures": [
    {
      "test": "test_api_misuse_0",
      "error": "429 errors",
      "file": "src/data/model_78.py",
      "line": 185
    },
    {
      "test": "test_api_misuse_1",
      "error": "Requests blocked",
      "file": "src/data/model_78.py",
      "line": 197
    }
  ]
}